name: "Build and Deploy"
on:
  push:
    branches:
      - "main"
    paths:
      - "**.md"
      - "_config.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write  # This is required for requesting the JWT to access AWS
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "deployment"
  cancel-in-progress: true

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::716182248480:role/Github-Actions-IDP
          role-session-name: github-actions-deployment

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll b -d "_site"
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            \-\-disable-external \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Deploy to AWS Cloudfront
        run: |
          aws s3 sync _site s3://${{ vars.AWS_BUCKET_NAME }}/my-website --delete --quiet --only-show-errors --exclude 'IaC/*'
          aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_DISTRIBUTION_ID }} --paths "/*"
