name: "Release"

permissions: read-all

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: ${{ github.event_name == 'pull_request'}}
          ci: ${{ github.event_name != 'pull_request'}}
